### ISSUE TITLE
oci_error -> infinite loop

### ISSUE THREAD

**Issue by dabretin** [huwwynnjones/oci_rs#2]
Hello !
In `oci_errors`, fn `get_error` the loop can be infinite when error occurs while trying to get the db error.
I think in match, it should break the loop for `ReturnCode::Error` and `ReturnCode::InvalidHandle` cases...

In my platform (fedora) it loops infinitly

**Comment by tatref** [comment]
I think I have the same issue.

Full code:
```
extern crate oci_rs;

use oci_rs::connection::Connection;

fn main() {
    let conn = Connection::new("localhost:1521/xe", "oci_rs", "test").unwrap();
}
```

Note that I have no database running on localhost, so an error is expected.

- OS: fedora 25 or 26, 64 bits
- RPM: oracle-instantclient12.2-devel-12.2.0.1.0-1

Running the above code on nightly, or current stable produces an OOM.

**Comment by huwwynnjones** [comment]
Hello,

Yes, I remember getting something like this when i was setting up the database, i forgot about it once i had the connection up and running. You are right, using a wrong username/password, or having no db available should return an error.

I will take a look.

**Comment by huwwynnjones** [comment]
Ok, i found the problem. I was sending the wrong handle into the get_error function in  line 384 in connection.rs

Bad code:

`    match connect_result.into() {
        ReturnCode::Success => Ok(()),
        _ => Err(get_error(
            error as *mut c_void,
            HandleType::Environment,
            "Database connection",
        )),
    }
`

Fixed code:

`    match connect_result.into() {
        ReturnCode::Success => Ok(()),
        _ => Err(get_error(
            error as *mut c_void,
            HandleType::Error,
            "Database connection",
        )),
    }
`

Once i switched to the error handle instead of the environment handle it correctly picks up an error. When the connection string is incorrect for example we should get an ORA-12514 TNS listener error.

I have added two tests, one to check wrong password and another to check for a TNS listener error. For the TNS error I pass in an incorrect connection string.

The latest code is pushed to master now, but not yet on cargo.io
